### ISSUE TITLE
Using wired SC

### ISSUE THREAD

**Issue by Sayanel01** [kozec/sc-controller#161] opened 2017-01-14 09:24 UTC
So far, sc-controller doesn't seems to work when the steam controller is wired.
Any way to fix that ?

**Comment by kozec** [comment] 2017-01-14 09:40
It should.

Turn off everything, run `scc-daemon debug` from terminal and check for any error messages.
It should output something like this when wired controller is connected:

```
D USB           USB device added: 28de:1102
D OSD DaemonCtrlr   Daemon is ready.
D SCCable       Got wired SC with serial FC54004D62
D SCCDaemon     Assigned default_mapper to <SCByCable scFC11004D61>
D SCCDaemon     Controller added: <SCByCable scFC11004D61>
D OSD DaemonCtrlr   Daemon reported profile change: /blaah/Desktop.sccprofile
I XI            Deatached device 14 from its master
```

**Comment by Sayanel01** [comment] 2017-01-14 10:21
Here is what I obtained : 
[code]
phil@Deepthought ~ $ scc-daemon debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
D USB           Registered hotplug USB driver for 28de:1102
D USB           Registered hotplug USB driver for 28de:1142
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7f8ce3c82750>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7f8ce3c33e50>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7f8ce3c15250>
D SCCDaemon     Created control socket /home/phil/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0
E USB           Failed to claim USB device 28de:1102 : LIBUSB_ERROR_BUSY [-6]
D OSD DaemonCtrlr   Connected to daemon, version 0.3.4.1
D OSD DaemonCtrlr   Daemon reported profile change: /home/phil/.config/scc/profiles/XBox Controller - Rocket League.sccprofile
D OSD DaemonCtrlr   Daemon reported error 'Failed to claim USB device: LIBUSB_ERROR_BUSY [-6]'
Erreur de segmentation
D OSD DaemonCtrlr   Connection to daemon lost
E OSD osd.daemon    Connection to daemon lost
[/code]

Error seems to appear after this line :
[code]E USB           Failed to claim USB device 28de:1102 : LIBUSB_ERROR_BUSY [-6] [/code]

**Comment by kozec** [comment] 2017-01-14 22:09
Yes, that's definitely problem. Check if you don't have Steam or multiple instances of scc-daemon running.

**Comment by Kierek** [comment] 2017-01-15 22:31
I've decided to check it and it seems that it also doesn't work for me(it used to about 2 weeks ago when my batteries died on me while playing)

> [kierek@kierekDesktop ~]$ scc-daemon debug
D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
D USB           Registered hotplug USB driver for 28de:1102
D USB           Registered hotplug USB driver for 28de:1142
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7fc17f63c990>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7fc17f63cd90>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7fc17f63cc10>
D SCCDaemon     Created control socket /home/kierek/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0
D USB           USB device added: 28de:1142
D OSD DaemonCtrlr   Connected to daemon, version 0.3.4.1
D OSD DaemonCtrlr   Daemon reported profile change: /home/kierek/.config/scc/profiles/Desktop.sccprofile
D OSD DaemonCtrlr   Daemon is ready.
I SCCDaemon     Registered scc-osd-daemon
I OSD osd.daemon    Sucessfully registered as scc-osd-daemon
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/usr/lib/python2.7/site-packages/scc/lib/usb1.py", line 2399, in wrapped_callback
    event,
  File "/usr/lib/python2.7/site-packages/scc/drivers/usb.py", line 230, in on_hotplug_event
    self.handle_new_device(device)
  File "/usr/lib/python2.7/site-packages/scc/drivers/usb.py", line 244, in handle_new_device
    handled_device = self._known_ids[tp](device, handle)
  File "/usr/lib/python2.7/site-packages/scc/drivers/sc_by_cable.py", line 28, in cb
    return SCByCable(device, handle, daemon)
  File "/usr/lib/python2.7/site-packages/scc/drivers/sc_by_cable.py", line 45, in __init__
    self.read_serial()
  File "/usr/lib/python2.7/site-packages/scc/drivers/sc_dongle.py", line 226, in read_serial
    if len(self._driver._available_serials) > 0:
AttributeError: 'SCByCable' object has no attribute '_available_serials'

**Comment by kozec** [comment] 2017-01-15 23:13
> It does work when I have Use Serial Numbers to Identify Controllers checked, but then no window opens when I click "configure controller".

1st one is easy, but can you try running gui from terminal and check if there is any error message displayed when you click that "configure controller" option?

**Comment by Spigerz** [comment] 2017-01-16 04:57
I'm having the same problem it seems two instances of scc-deamon are running on start up `restart and end`,  `Use Serial Numbers to Identify Controllers` bypasses it

**Comment by kozec** [comment] 2017-01-16 07:06
> I'm having the same problem it seems two instances of scc-deamon are running on start up

That's most likely cause of problem. Just close GUI, kill them both and start GUI again.

**Comment by kozec** [comment] 2017-01-16 07:07
By the way, that crash that @Kierek observed should be fixed by 1446c8cd8cb0abb78ccfbd894284893e6a0473d9, I just forgot to add Ref: to this issue.

**Comment by Kierek** [comment] 2017-01-16 07:50
> 1st one is easy, but can you try running gui from terminal and check if there is any error message displayed when you click that "configure controller" option?

Sure:

> [kierek@kierekDesktop ~]$ sc-controller 
> Gdk-Message: Window 0x55f42dd20b10 is a temporary window without parent, application will not be able to position it on screen.
> Gdk-Message: Window 0x55f42dd20b10 is a temporary window without parent, application will not be able to position it on screen.
> 
> (sc-controller:2231): Gdk-CRITICAL **: xdg_popup_configure: assertion 'impl->transient_for' failed
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/scc/gui/app.py", line 772, in on_mnuConfigureController_activate
>     cs = ControllerSettings(self, mnuPS.ps.get_controller(), mnuPS.ps)
>   File "/usr/lib/python2.7/site-packages/scc/gui/controller_settings.py", line 31, in __init__
>     self.load_settings()
>   File "/usr/lib/python2.7/site-packages/scc/gui/controller_settings.py", line 95, in load_settings
>     txName.set_text(cfg["name"])
> TypeError: Argument 1 does not allow None as a value
> W UDataManager  enumerate_children_finish for /home/kierek/.config/scc/controller-icons failed: g-io-error-quark: Error opening directory '/home/kierek/.config/scc/controller-icons': No such file or directory (1)


And about this: 
> I'm having the same problem it seems two instances of scc-deamon are running on start up restart and end, Use Serial Numbers to Identify Controllers bypasses it

It seems to be a part of a bigger problem. Sometimes I experience appearance of the second and even third scc-daemon. I'm still trying to find a way to reproduce it, but it probably have something to do with quick profile changing by actions and the fact that xbox 360 controller is connected. After it happens, my Steam Controller changes name and icon in sc-controller. I have to kill all daemons, GUI and start it again to fix it.

**Comment by kozec** [comment] 2017-01-16 08:33
> I'm still trying to find a way to reproduce it, but it probably have something to do with quick profile changing by actions and the fact that xbox 360 controller is connected.

I don't thing xbox controller should have any effect on SCC, unless it does something really crazy, like generating heavy noise signal on USB bus... But quick profile changing _may_ cause something to clash. If you are trying to reproduce it, run `scc-daemon debug` before GUI, so you can see errors.

**Comment by kozec** [comment] 2017-01-16 08:38
Anyway, @Sayanel01, are you running code from git or packaged version? If former, there is a chance wired controller will work for you now.

**Comment by kozec** [comment] 2017-01-21 09:32
Ok, I believe this was fixed in Tuesday release. Please, reopen if I'm mistaken.

**Closed by kozec** 2017-01-21 09:32 UTC
