### ISSUE TITLE
Rumble support?

### ISSUE THREAD

**Issue by Kierek** [kozec/sc-controller#141] opened 2017-01-05 14:04 UTC
Is it possible to add rumble feedback feature? It works great with the original Steam Client and Dolphin emulator.

**Comment by Kierek** [comment] 2017-01-05 14:38
Whoops, you might be right. I'm not sure now if I wasn't using rumble through my virtualized Windows installation.

**Comment by richese** [comment] 2017-01-05 15:43
Steam has experimental rumble support. I have not tested it under Linux because ETS2 has bugged SC support with steam driver under linux...
![rumble](https://cloud.githubusercontent.com/assets/8769724/21686471/d9430918-d365-11e6-95ae-b9b5df4e136e.png)

**Comment by kozec** [comment] 2017-01-07 11:26
So, I merged that old code with current master and put everything in [https://github.com/kozec/sc-controller/tree/rumble](rumble branch). It kind-of works.

Now, if anyone knows about _any_ game for linux, or even better actual testing application that generates haptic feedback, I would be really glad to know, because so far, I found nothing :(

**Comment by Kierek** [comment] 2017-01-07 11:29
Dolphin emulator is probably your best bet. On my original Xbox 360 controller I can conveniently set rumble settings.
![zrzut ekranu z 2017-01-07 12-28-49](https://cloud.githubusercontent.com/assets/4080084/21741405/e03af35a-d4d4-11e6-9214-50b0e302ee6b.png)

**Comment by kozec** [comment] 2017-01-07 11:30
Looks great, thanks. Installing right now...

**Comment by kozec** [comment] 2017-01-07 22:56
Sooo... On my machine, Dolphin now does same thing with Steam Controller as it does with PS3 controller. Weird thing is that it does same thing for all effect types.

Can you please check if there is any difference with Xbox pad? Does it matter if you add effect for Sine or Square, for example?

**Comment by Kierek** [comment] 2017-01-08 09:24
It's strange, but all effects work exactly the same, it's always been like that. I assumed that it has something to do with there only being one motor in my controller but I see that it's not the case here.

I took his explanation for granted:
https://forums.dolphin-emu.org/Thread-steelseries-3gc-controller-rumble?pid=329307#pid329307

**Comment by kozec** [comment] 2017-01-08 21:37
Ok, I tested it a little, added config, enabled it by default and merged to master, so those poor souls running SCC from git can test what it broke :)

By the way, @richese, I've tried Steam implementation in meantime and I believe that "Enable experimental rumble" option does nothing, as emulated pad reports no rumble support. Maybe it's another Windows only thing :(

**Comment by Kierek** [comment] 2017-01-08 23:30
It works kinda... strange. When testing it with dolphin emulator configuration or via `sdl2-jstest` it does not always fire the rumble. At least not until I touch left or right pad, is the controller falling into some kind of power saving mode?

While playing the game, the haptics vibrate always in the same manner. No difference in power, pattern, length. On xbox pad they were easily distinguishable, e.g. one short and powerful, another weaker and longer, on Steam Controller they feel exactly the same.

**Comment by kozec** [comment] 2017-01-09 00:08
> At least not until I touch left or right pad, is the controller falling into some kind of power saving mode?

Yes, SC stops receiving any commands if no buttons are pressed for a while. There is not much to do with that, as it's HW limitation, but it shouldn't be a problem during gameplay.

> I'm aware that we have no motors, but they should be at least a little bit different, shouldn't they?

Possibly yes. Can you give me example? What game are you playing?

**Comment by Kierek** [comment] 2017-01-09 10:21
> Possibly yes. Can you give me a example? What game are you playing?

It can easily be tested with Mario Kart Wii, but it acts the same in all games.

In Mario Kart almost anything you do in menu will respond with a rumble(at least on emulated Gamecube Controller). If you have another pad with normal motors, set it up as the second controller and run 2 player game. In character selection menu you'll be easily able to see how different the two pads respond. 

Also, while playing the actual race, there's no difference between hitting another player, picking up the power up or getting turbo from drifting.

**Comment by kozec** [comment] 2017-01-10 19:13
Ok, at this point, I'm not really sure what I'm doing :D

But. I found that dolphin sends always exactly same FF_PERIODIC rumble events, but it sends them short and few in a row. It basically emulates what gamepad should do by itself... So I tweaked conversion to allow those short events and I believe it's fairly similar to what PS3 pad does.

**Comment by Kierek** [comment] 2017-01-10 20:19
Wow, you're a magician, it works great in Mario Kart, but now it seems that testing in settings(still in dolphin menu) and using `sdl2-jstest -r 0` seems to be broken, it doesn't vibrate at all or just slightly.

> (also, I during testing, I got my ass handed by baby Peach three times in a row, so now, I'm depressed... )

I know this pain too well :D

**Comment by GlacialTurtle** [comment] 2017-01-11 00:36
I just tried it in Escape Goat 2, rumble happens when you do a dash into a wall, but the rumble just keeps going and doesn't stop for a long time (~30 seconds or so) unless you turn off the controller. In Dolphin it seems to work as you'd expect.

**Comment by Kierek** [comment] 2017-01-11 12:46
> Edit: Also, Hyper Light Drifter claims to have rumble support, but no rumble happens in game.

The same happens with Retroarch's Mednafen PSX core, rumble works fine on Xbox 360 controller, but no rumble on the SC.

**Comment by kozec** [comment] 2017-01-11 12:50
So, just to be clear, those two are detecting that rumble is supported, but no effects are generated, or they don't see emulated gamepad as one with rumble support at all?

**Comment by Kierek** [comment] 2017-01-11 12:53
I'm not sure if I can check if rumble is supported in retroarch, but sdl2-jstest definitely sees Steam Controller as one that can support it. It just doesn't vibrate while firing the test.

**Comment by GlacialTurtle** [comment] 2017-01-11 16:05
Here's the relevant terminal output from Hyper Light Drifter: 
```
INFO: Device Plugged In [0]
INFO: Input created joystick device
INFO: Input detects expected haptic support.
INFO: Game Controller Setup: mapping[030000005e0400008e02000010010000,X360 Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Linux,]
Set JID to plugged in gamepad -- X360 Controller
FOUND SOME RANDOM CONTROLLER
X360 Controller
```
Another oddity with Escape Goat 2:

If you do the dash into a wall again while the haptics are already firing off, you can hear it do another rumble, but this time it does it for the time you'd expect (half a second or so) but simply in addition to the rumble it's already doing. No decent terminal output for it.

Both games use SDL2.

**Comment by kozec** [comment] 2017-01-11 23:14
Ok, so I kinda ended up parsing SDL2 source code and writing 'receiving' part around it, but there is good chance other libraries are doing the same.

**Comment by kozec** [comment] 2017-01-12 00:03
About Hyper Light Drifter, does it works with anything else? Because it appears to:

1. Send "stop rumble" commands all the time
2. Setup rumble effect from time-to-time (for example when character suicides), but never firing setup effect.

And I'm wondering if that is bug in game, engine, or something I missed...

**Comment by Kierek** [comment] 2017-01-12 15:44
A little update about RetroArch. When I've changed my joypad driver from udev to sdl2 the Steam Controller started vibrating constantly, I had to disable emulation to stop it.

**Comment by GlacialTurtle** [comment] 2017-01-12 18:52
> About Hyper Light Drifter, does it works with anything else? Because it appears to:
>
>    Send "stop rumble" commands all the time
>    Setup rumble effect from time-to-time (for example when character suicides), but never firing that >effect.
>
>And I'm wondering if that is bug in game, engine, or something I missed...

I don't have any other rumble supporting controllers to test sadly, only an F310. In this thread on the Steam forums there are people reporting problems with the recent versions of the game apparently caused by a problem in the games version of SDL2:

http://steamcommunity.com/app/257850/discussions/1/365163686036494421/?ctp=12

I'm on the GOG version which is a few months behind on the available Linux version.

With the latest changes Escape Goat 2 doesn't rumble anymore. I'll see if I can find any other games to test.

**Comment by kozec** [comment] 2017-01-12 21:45
Ok, with above, everything that is _not_ Hyper Light Drifter should work.

About that one, I'm not sure. I could probably add workaround that would prevent it from setuping one event ID and firing other, but I'm not sure how to do it in way that wouldn't affect other games.

**Comment by GlacialTurtle** [comment] 2017-01-13 00:16
Just tested with Escape Goat 2, Towerfall Ascension and Dolphin and it works here at least.

Don't worry about Hyper Light Drifter, their bug, their problem :p

Also, in about a week you've implemented a feature that Valve hasn't for months on Linux, keep up the good work!

**Comment by Kierek** [comment] 2017-01-13 00:18
> Also, in about a week you've implemented a feature that Valve hasn't for months on Linux, keep up the good work!

This so much, really impressive. Works perfect for all my usecases, thanks!

**Comment by kozec** [comment] 2017-01-16 23:08
Well, I had better testers :)

Rumble is now enabled by default in latest release, so this can be pronounced done.

**Closed by kozec** 2017-01-16 23:08 UTC

**Comment by kozec** [comment] 2017-01-19 21:53
Thanks to @Ryochan7's finding how their rumble generation works, SCC is now compatible with rumble in Saints Row 4, Borderlands and that cursed Hyper Light Drifter as well :)
