### ISSUE TITLE
Newly created profile does not show up in the selector

### ISSUE THREAD

**Issue by meschi** [kozec/sc-controller#282] opened 2017-11-06 23:17 UTC
I am running run.sh from the zip download on Ubuntu 17.10.

When i create a new profile, the drop down menu does not contain the newly created profile. when i restart the application the profiles get displayed.

**Comment by LinuxJoeUser** [comment] 2017-11-07 13:05
I can confirm this behaviour in Xubuntu 17.10.

**Comment by LinuxJoeUser** [comment] 2017-11-08 13:45
Hmmmm.  It might have something to do with running SCC using ./run.sh, *without having installed it* (via `python2 setup.py build`, etc.) because that's how I'd been running it when I was having this problem.  But now that I've installed it to be able to run it as `sc-controller -d` the problem is gone, whether I run it as `sc-controller` or via `./run.sh`.  So maybe to reproduce, use a fresh clone from github and only run it with ./run.sh?

btw, I've been keeping my version the very latest by using `git pull` and running that with `./run.sh` ... I thought that if I installed SCC then I'd be unable to continue to simply use `git pull` to update things, that the built and installed `sc-controller` wouldn't be updated.  Am I right about that?

**Comment by kozec** [comment] 2017-11-08 15:03
>  I thought that if I installed SCC then I'd be unable to continue to simply use git pull to update things, that the built and installed sc-controller wouldn't be updated. Am I right about that?

You should be able to have system-wide installation and git checkout at once with no problem, at worse some icons will be displayed wrong. And git checkout breaking when there is no system-wide install shouldn't be a thing as well, so I'll check on that.

**Comment by LinuxJoeUser** [comment] 2017-11-10 13:42
Could this issue could be closed if a mention this behaviour were mentioned in the README.md?  Something like:

##### To run without package
- download and extract [latest release](https://github.com/kozec/sc-controller/releases/latest)
- navigate to extracted directory and execute `./run.sh`
-*Note:  Running SCC in this way will cause newly created profiles to not show up until SCC is restarted.*

I'm just thinking that this "issue" isn't a fault of SCC but, like not being able to debug by running `sc-controller -d`, or not having an icon to launch SCC with, this is just a shortcoming of using `./run.sh` to start SCC.  I'm inclined to say close this issue with a note added to the README.md.  Of course, it's up to you. :)

**Closed** 2017-12-23 11:27 UTC
