### ISSUE TITLE
Bluetooth support for Steam Controller

### ISSUE THREAD

**Issue by neoman4426** [kozec/sc-controller#365] opened 2018-05-12 09:49 UTC
Obviously don't expect it to already work since it was just released, but figured I'd leave an issue here for completeness sake. At least on the beta branch of Steam a firmware update has been released for the controller that allows it to connect in Bluetooth mode or the proprietary communication the official dongle uses. If connecting in Bluetooth mode this program does not hook the inputs from the controller and it continues to use lizard mode.

**Comment by DFOXpro** [comment] 2018-05-12 19:11
The BLE device interface of the SC (is diferent of the tandem usb mode)
![imagen](https://user-images.githubusercontent.com/5248241/39960776-3eaa7726-55ee-11e8-9dc9-9a3257eb9f93.png)

**Comment by neoman4426** [comment] 2018-05-14 21:31
There's a page in their knowledge base that includes a link to open the firmware update dialog, could be helpful https://support.steampowered.com/kb_article.php?ref=7728-QESJ-4420

**Comment by parkerlreed** [comment] 2018-05-18 15:43
@kozec Is enough exposed in the sccbt branch to test this out? I installed it and I have `sc_by_bt` in the config by default but it doesn't seem to do anything from there.

**Comment by MayeulC** [comment] 2018-05-18 16:38
This might be out of scope (for now, at least), but as far as I know, there is no way to configure the steam controller on Android. How hard would a sc-controller port be? (At first, only loading profiles created on the computer should be enough)

**Comment by parkerlreed** [comment] 2018-05-18 17:11
@MayeulC there seems to already be some work for Android (although looks to have not been touched in a  while) https://github.com/kozec/sc-controller/tree/android

**Comment by kozec** [comment] 2018-05-18 20:06
Android is little bigger issue that I thought originally, pretty-much nothing SCC has right now works there. Different input system, different input emulation, GTK can't work there, python can't work there...

Anyway, if someone feels really, but really adventurous, Steam Controller over BT support is merged to master. Now I'm going to play with if for entire weekend and hopefully catch all bugs :)

**Comment by kozec** [comment] 2018-05-21 13:31
> Nothing in the console output that would suggest any errors (Just an http error for the release notes)

That's probably output from gui, try running `scc-daemon debug` from console.

**Comment by parkerlreed** [comment] 2018-05-21 13:46
Couple things I've noticed so far:

1. Daemon has to be toggled if controller (dis)connected

2. Feedback seems to not be working (works wired)

**Comment by kozec** [comment] 2018-05-21 13:50
Everything you wrote sounds like you are two-three commits behind :)

**Comment by parkerlreed** [comment] 2018-05-21 15:00
If I disconnect the controller from the system Bluetooth menu or via "Turn off controller" in the guide overlay, power back on and connecting back the daemon has to be restarted. It doesn't pick up the Bluetooth connection midway (That's what I was referring to with my first bullet point earlier)

**Comment by kozec** [comment] 2018-05-21 21:10
> If I disconnect the controller from the system Bluetooth menu or via "Turn off controller" in the guide overlay, power back on and connecting back, the daemon has to be restarted.

Well, that was one heck of thing to replicate, mine does it about one times out of ten :)

**Comment by parkerlreed** [comment] 2018-05-21 21:36
Success!

````
D OSD DaemonCtrl    Connected to daemon, version 0.4.2
D OSD DaemonCtrl    Daemon reported profile change for scbt1: /usr/share/scc/default_profiles/Desktop.sccprofile
D OSD DaemonCtrl    Daemon is ready.
I SCCDaemon     Registered scc-osd-daemon
I OSD osd.daemon    Sucessfully registered as scc-osd-daemon
D SCCDaemon     Controller removed: <SCByBt scbt1>
E SCBT          [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scc/drivers/sc_by_bt.py", line 95, in new_device_callback
    return SCByBt(self, syspath, dev)
  File "/usr/lib/python2.7/site-packages/scc/drivers/sc_by_bt.py", line 124, in __init__
    self.flush()
  File "/usr/lib/python2.7/site-packages/scc/drivers/sc_by_bt.py", line 230, in flush
    self._hidrawdev.sendFeatureReport(msg)
  File "/usr/lib/python2.7/site-packages/scc/lib/hidraw.py", line 120, in sendFeatureReport
    True,
  File "/usr/lib/python2.7/site-packages/scc/lib/hidraw.py", line 59, in _ioctl
    result = fcntl.ioctl(self._device, func, arg, mutate_flag)
IOError: [Errno 5] Input/output error
E SCBT          Read Failed
D SCCDaemon     Controller removed: <SCByBt scbt1>
D SCBT          Reconnecting to controller...
D SCCDaemon     Assigned default_mapper to <SCByBt scbt1>
D SCCDaemon     Controller added: <SCByBt scbt1>
E SCBT          Read Failed
D SCCDaemon     Controller removed: <SCByBt scbt1>
D OSD DaemonCtrl    Daemon reported profile change for scbt1: /usr/share/scc/default_profiles/Desktop.sccprofile
D SCBT          Reconnecting to controller...
D SCCDaemon     Assigned default_mapper to <SCByBt scbt1>
D SCCDaemon     Controller added: <SCByBt scbt1>
D OSD DaemonCtrl    Daemon reported profile change for scbt1: /usr/share/scc/default_profiles/Desktop.sccprofile
````

Thanks for all the updates!

**Comment by parkerlreed** [comment] 2018-05-21 21:51
Another :P 

When invoking the keyboard, wired USB works fine, but Bluetooth has erratic movements. I'm not sure if this only applies to the keyboard or when using both pads in general.

https://www.youtube.com/watch?v=ZfyC08lblxo

**Comment by kozec** [comment] 2018-05-22 20:09
> https://www.youtube.com/watch?v=ZfyC08lblxo

[Heh.](http://i.imgur.com/HTisMpC.jpg?fb) That was caused by that fix before :)

**Comment by parkerlreed** [comment] 2018-05-22 22:01
@kozec :D That fixed the "touching only right pad moves left pad"

The issue when both are being held down making them jittery is still there.

**Comment by kozec** [comment] 2018-05-23 20:59
Well, I haven't said I'm finished.

**Comment by parkerlreed** [comment] 2018-05-23 21:47
Understand :) I'll be quiet for a bit and marvel in the amazing work that is being done ;D

Thanks again.

**Comment by kozec** [comment] 2018-05-25 14:59
[... aaand it's done.](https://github.com/kozec/sc-controller/releases/tag/v0.4.3)

@parkerlreed, thank you very much for testing, I'd be still dancing around three machines without it :)

**Closed by kozec** 2018-05-25 14:59 UTC
